Sum

In [2]:
a=10
b=20
print(a+b)

30


In [1]:
print("Hello")

Hello


In [1]:
import numpy as np

In [11]:
arr1=np.array([1,2,3,4,5])
arr2=arr1+1
arr1[:]=10
arr1[1:3]=[20,30]
arr1

array([10, 20, 30, 10, 10])

In [ ]:
arr1.shape  # used to find number of element in dimenssions
arr1.ndim   # used to find the number of dimensions

1

In [ ]:
 # when crating with different data type , then change it to a same datatype
#  in this case it change all numbers to string
arr2=np.array([1,2,3,4,5,6,"Hello"]) 
arr2
arr2=np.array([1,2,3,4,5,6,True,False])
arr2
# array cannot add a new element or delete existing , but can manipulate

array([1, 2, 3, 4, 5, 6, 1, 0])

2D Arrays

In [ ]:
arr3=np.array([[1,2,3,4],[5,200,3,1],[3,2,1,2],[5,6,7,8]])
arr3.shape
arr3.ndim
arr3.size
arr2.dtype
arr3[1][1]=40
arr3[1,1]=10
arr3[:,2]
arr3[1:3,1:3]=0
arr3

array([[1, 2, 3, 4],
       [5, 0, 0, 1],
       [3, 0, 0, 2],
       [5, 6, 7, 8]])

In [ ]:
arr4=np.array([[1,2,3],[4,5,6],[11,12,13],
               [9,8,7],[10,20,30],[66,77,88],[53,55,57]])
arr4
arr4[:,::2]
arr4[::6,::2]=-1
arr4

array([[-1,  2, -1],
       [ 4,  5,  6],
       [11, 12, 13],
       [ 9,  8,  7],
       [10, 20, 30],
       [66, 77, 88],
       [-1, 55, -1]])

Advanced indexing

In [ ]:
arr4[[0,1,5],[1,1,1]]
arr4[[0,1,5],[0,0,0]]=[100,200,300]
#Acces 1st 2, 3 row and change value into 2 55
arr4[[0,1,5]]=[255]
arr4

array([255, 255, 255, 255, 255, 255,  11,  12,  13,  20,  30, 255, 255,
       255,  55])

boolean indexing

In [93]:
arr4>20
arr4[arr4>10]
arr4[arr4%2==0]


array([12,  8, 10, 20, 30])

editting for git learning
